import {
  LayoutDashboard,
  Users,
  UserPlus,
  UserCheck,
  CalendarCheck,
  CalendarDays,
  CreditCard,
  TrendingUp,
  Crown,
  Sparkles,
  ShieldCheck,
  BarChart3,
  Layers,
  Settings,
  Briefcase,
  FileCheck,
  Gift,
  Clock,
  Clock3,
  MapPin,
  Clock4,
  Receipt,
  FileText,
  Percent,
  Target,
  Award,
  MessageSquare,
  Medal,
  Bot,
  Zap,
  Brain,
  Cpu,
  FileLock,
  History,
  FolderLock,
  AlertTriangle,
  Users2,
  DollarSign,
  Calendar,
  FileSpreadsheet,
  Key,
  Database,
  MessageCircle,
  Code2,
  Building,
  Shield,
  Lock,
  CreditCard as BillingIcon,
  FolderTree,
  Building2,
  BadgeCheck,
  Contact,
  Package,
  Laptop,
  RotateCcw,
  FilePlus,
  Wrench,
  Store,
  ClipboardCheck,
  Download,
  GraduationCap,
  TrendingDown,
  Activity,
  SlidersHorizontal,
  Megaphone,
  Ticket,
  Radio,
  Newspaper,
  PartyPopper,
  CheckSquare,
  ScrollText,
  Handshake,
  HeartHandshake,
  BookOpen,
  GitPullRequest,
  Mail,
  BarChart2,
  FileCode,
} from "lucide-react";


export interface SubModuleItem {
  id: string;
  title: string;
  description: string;
  href: string;
  icon: any;
  stats?: string;
  statusBadge?: string;
}

export interface SidebarNavItem {
  id: string;
  title: string;
  href: string;
  icon: any;
  description: string;
  subModules: SubModuleItem[];
}

export const SIDEBAR_NAV_ITEMS: SidebarNavItem[] = [
  {
    id: "dashboard",
    title: "Dashboard",
    href: "/dashboard",
    icon: LayoutDashboard,
    description: "Enterprise workforce command center & real-time telemetry",
    subModules: [],
  },
  {
    id: "workforce",
    title: "Workforce",
    href: "/dashboard/workforce",
    icon: Users,
    description: "Manage employee directory, organizational hierarchy, departments & branches",
    subModules: [
      {
        id: "employees",
        title: "Employees",
        description: "Full directory of active workforce, profiles, and employment contracts",
        href: "/dashboard/workforce/employees",
        icon: Contact,
        stats: "Active Directory",
        statusBadge: "Updated Today",
      },
      {
        id: "executives",
        title: "Executive Leadership",
        description: "Corporate governance, C-Suite officers, Vice Presidents, and strategic enterprise decision-makers",
        href: "/dashboard/workforce/executives",
        icon: Crown,
        stats: "C-Suite & VPs",
        statusBadge: "Leadership",
      },
      {
        id: "managers",
        title: "Managers Directory",
        description: "Dedicated directory of team leaders, department heads, and managers",
        href: "/dashboard/workforce/managers",
        icon: UserCheck,
        stats: "Leadership Hub",
        statusBadge: "Management",
      },
      {
        id: "departments",
        title: "Departments",
        description: "Business units, cost centers, and departmental leadership structure",
        href: "/dashboard/workforce/departments",
        icon: Building2,
        stats: "18 Departments",
        statusBadge: "Active",
      },
      {
        id: "designations",
        title: "Designations",
        description: "Job titles, pay bands, grade levels, and career progression frameworks",
        href: "/dashboard/workforce/designations",
        icon: BadgeCheck,
        stats: "42 Roles",
        statusBadge: "Standardized",
      },
      {
        id: "branches",
        title: "Branches",
        description: "Office locations, global campuses, legal entities, and physical sites",
        href: "/dashboard/workforce/branches",
        icon: Building,
        stats: "8 Locations",
        statusBadge: "Global",
      },
      {
        id: "org-chart",
        title: "Organization Chart",
        description: "Interactive reporting hierarchy, reporting trees, and team structures",
        href: "/dashboard/workforce/org-chart",
        icon: FolderTree,
        stats: "Live Visualizer",
        statusBadge: "Interactive",
      },
    ],
  },
  {
    id: "recruitment",
    title: "Recruitment",
    href: "/dashboard/recruitment",
    icon: UserPlus,
    description: "End-to-end ATS, job openings, Kanban candidate pipeline, interviews, AI copilot & offer workflows",
    subModules: [
      {
        id: "requisitions",
        title: "Requisitions",
        description: "Headcount requests, budget allocation, and hiring manager approval workflows",
        href: "/dashboard/recruitment/requisitions",
        icon: FileText,
        stats: "Budget & Approvals",
        statusBadge: "Headcount",
      },
      {
        id: "jobs",
        title: "All Jobs",
        description: "Post, edit, and publish job requisitions across internal and public career portals",
        href: "/dashboard/recruitment/jobs",
        icon: Briefcase,
        stats: "Active Requisitions",
        statusBadge: "Hiring",
      },
      {
        id: "candidates",
        title: "Candidates",
        description: "Comprehensive applicant profiles, resume scorecards, and candidate database",
        href: "/dashboard/recruitment/candidates",
        icon: UserCheck,
        stats: "Talent Pool",
        statusBadge: "Active Pipeline",
      },
      {
        id: "pipeline",
        title: "Kanban Pipeline",
        description: "Drag-and-drop applicant pipeline board across hiring stages",
        href: "/dashboard/recruitment/pipeline",
        icon: GitPullRequest,
        stats: "Visual Board",
        statusBadge: "Drag & Drop",
      },
      {
        id: "interviews",
        title: "Interviews",
        description: "Interview scheduler, panel assignments, meeting links, and scorecards",
        href: "/dashboard/recruitment/interviews",
        icon: Clock,
        stats: "Panels & Schedules",
        statusBadge: "Scheduled",
      },
      {
        id: "copilot",
        title: "AI Recruiter Copilot",
        description: "AI-assisted resume screening, candidate match scoring, and JD generation",
        href: "/dashboard/recruitment/copilot",
        icon: Sparkles,
        stats: "AI Assistant",
        statusBadge: "AI Powered",
      },
      {
        id: "offers",
        title: "Offers & Contracts",
        description: "Offer letter generation, salary modeling, approval chains, and acceptance tracking",
        href: "/dashboard/recruitment/offers",
        icon: Gift,
        stats: "Comp & Approvals",
        statusBadge: "Action Required",
      },
      {
        id: "onboarding",
        title: "Onboarding Handover",
        description: "New hire provisioning, welcome checklists, document verification, and buddy assignment",
        href: "/dashboard/recruitment/onboarding",
        icon: UserPlus,
        stats: "Handover Tracker",
        statusBadge: "Provisioning",
      },
      {
        id: "crm",
        title: "Candidate CRM",
        description: "Automated candidate nurturing campaigns, email sequences, and relationship history",
        href: "/dashboard/recruitment/crm",
        icon: Mail,
        stats: "Nurturing Hub",
        statusBadge: "Outreach",
      },
      {
        id: "talent-pool",
        title: "Talent Pool",
        description: "Silver-medalist inventory, secondary applicant profiles, and skills search",
        href: "/dashboard/recruitment/talent-pool",
        icon: Database,
        stats: "Skills Inventory",
        statusBadge: "Archive",
      },
      {
        id: "analytics",
        title: "Recruitment Analytics",
        description: "Stage conversion funnel, time-to-hire, cost-per-hire, and recruiter velocity",
        href: "/dashboard/recruitment/analytics",
        icon: BarChart2,
        stats: "Funnel Metrics",
        statusBadge: "Analytics",
      },
      {
        id: "templates",
        title: "Recruitment Templates",
        description: "Email templates, pipeline column configuration, and scorecard criteria",
        href: "/dashboard/recruitment/templates",
        icon: Settings,
        stats: "Configuration",
        statusBadge: "Settings",
      },
    ],
  },

  {
    id: "onboarding",
    title: "Onboarding",
    href: "/dashboard/onboarding",
    icon: UserCheck,
    description: "New hire provisioning, background checks, equipment setup & checklists",
    subModules: [
      {
        id: "workflows",
        title: "Workflows",
        description: "Automated onboarding sequences and department orientation playbooks",
        href: "/dashboard/onboarding/workflows",
        icon: Zap,
        stats: "5 Active Templates",
        statusBadge: "Automated",
      },
      {
        id: "new-hires",
        title: "New Hires",
        description: "Incoming employee tracker, start dates, and onboarding progress",
        href: "/dashboard/onboarding/new-hires",
        icon: UserPlus,
        stats: "12 Joining This Month",
        statusBadge: "On Track",
      },
      {
        id: "documents",
        title: "Document Verification",
        description: "Government IDs, educational verification, and tax tax forms collection",
        href: "/dashboard/onboarding/documents",
        icon: FileCheck,
        stats: "98% Verified",
        statusBadge: "Compliant",
      },
      {
        id: "tasks",
        title: "Task Checklists",
        description: "IT provisioning, badge access, workstation dispatch, and welcome kits",
        href: "/dashboard/onboarding/tasks",
        icon: CalendarCheck,
        stats: "45 Tasks Open",
        statusBadge: "In Progress",
      },
    ],
  },
  {
    id: "assets",
    title: "Asset Management",
    href: "/dashboard/assets",
    icon: Package,
    description: "Hardware inventory, asset allocation, returns, maintenance & category lifecycle",
    subModules: [
      {
        id: "inventory",
        title: "Asset Inventory",
        description: "Full registry of hardware, laptops, mobile devices, monitors & office assets",
        href: "/dashboard/assets/inventory",
        icon: Laptop,
        stats: "Live Registry",
        statusBadge: "Tracked",
      },
      {
        id: "assign",
        title: "Asset Assignment",
        description: "Allocate hardware to employees, assign serial numbers & track handovers",
        href: "/dashboard/assets/assign",
        icon: UserCheck,
        stats: "Deployments",
        statusBadge: "Active",
      },
      {
        id: "return",
        title: "Asset Return",
        description: "Process employee returns, check-in equipment, inspect state & wipe data",
        href: "/dashboard/assets/return",
        icon: RotateCcw,
        stats: "Check-ins",
        statusBadge: "Check-in",
      },
      {
        id: "requests",
        title: "Asset Requests",
        description: "Employee equipment requisitions, upgrade requests & approval workflows",
        href: "/dashboard/assets/requests",
        icon: FilePlus,
        stats: "Requisitions",
        statusBadge: "Action Required",
      },
      {
        id: "maintenance",
        title: "Maintenance & Repair",
        description: "Track servicing schedules, warranty claims, repair tickets & vendor RMAs",
        href: "/dashboard/assets/maintenance",
        icon: Wrench,
        stats: "Servicing",
        statusBadge: "In Repair",
      },
      {
        id: "vendors",
        title: "Vendors & Suppliers",
        description: "Hardware OEMs, authorized suppliers, warranty contracts & active SLAs",
        href: "/dashboard/assets/vendors",
        icon: Store,
        stats: "Suppliers",
        statusBadge: "Active SLAs",
      },
      {
        id: "categories",
        title: "Asset Categories",
        description: "Device taxonomies, hardware specifications & lifecycle policies",
        href: "/dashboard/assets/categories",
        icon: FolderTree,
        stats: "Taxonomies",
        statusBadge: "Standardized",
      },
      {
        id: "audit",
        title: "Stock Audit & Verification",
        description: "Physical inventory audits, barcode/QR verification & reconciliation",
        href: "/dashboard/assets/audit",
        icon: ClipboardCheck,
        stats: "Audits",
        statusBadge: "Verified",
      },
      {
        id: "reports",
        title: "Asset Reports",
        description: "Valuation analysis, depreciation schedules & custom data exports",
        href: "/dashboard/assets/reports",
        icon: BarChart3,
        stats: "Analytics",
        statusBadge: "Real-time",
      },
      {
        id: "vendor-management-hub",
        title: "Vendor Management",
        description: "Full vendor directory, contracts, and supplier performance",
        href: "/dashboard/vendors",
        icon: Store,
        stats: "Vendor Hub",
        statusBadge: "Linked",
      },
    ],
  },
  {
    id: "attendance",
    title: "Attendance",
    href: "/dashboard/attendance",
    icon: CalendarCheck,
    description: "Real-time time tracking, biometric logs, shift scheduling & overtime",
    subModules: [
      {
        id: "logs",
        title: "Daily Logs",
        description: "Real-time punch-in/out records, break times, and biometric sync",
        href: "/dashboard/attendance/logs",
        icon: Clock3,
        stats: "96.4% Present",
        statusBadge: "Real-time",
      },
      {
        id: "shifts",
        title: "Shifts & Schedules",
        description: "Rotational shift planning, night shifts, and roster management",
        href: "/dashboard/attendance/shifts",
        icon: Clock4,
        stats: "3 Shift Patterns",
        statusBadge: "Active",
      },
      {
        id: "geofence",
        title: "Geofencing & Biometrics",
        description: "GPS boundary tracking, mobile check-ins, and physical terminal sync",
        href: "/dashboard/attendance/geofence",
        icon: MapPin,
        stats: "12 Zones Active",
        statusBadge: "Secured",
      },
      {
        id: "overtime",
        title: "Overtime Approvals",
        description: "Extra hours calculation, manager approvals, and payout calculations",
        href: "/dashboard/attendance/overtime",
        icon: Receipt,
        stats: "8 Pending Approvals",
        statusBadge: "Review Needed",
      },
      {
        id: "leave-hub",
        title: "Leave",
        description: "Leave requests, balances, and approval workflows",
        href: "/dashboard/leave",
        icon: CalendarDays,
        stats: "Leave Center",
        statusBadge: "Linked",
      },
      {
        id: "approvals-hub",
        title: "Approvals",
        description: "Pending approval queue across the organization",
        href: "/dashboard/approvals",
        icon: CheckSquare,
        stats: "Approval Queue",
        statusBadge: "Linked",
      },
      {
        id: "calendar-hub",
        title: "Calendar",
        description: "Company holiday and event calendar",
        href: "/dashboard/calendar",
        icon: Calendar,
        stats: "Calendar View",
        statusBadge: "Linked",
      },
    ],
  },
  {
    id: "payroll",
    title: "Payroll",
    href: "/dashboard/payroll",
    icon: CreditCard,
    description: "Salary processing, statutory deductions, tax calculation & payslip distribution",
    subModules: [
      {
        id: "salary-structure",
        title: "Salary Structure",
        description: "Base pay, allowances, bonuses, ESOPs, and statutory components",
        href: "/dashboard/payroll/salary-structure",
        icon: CreditCard,
        stats: "12 Pay Grades",
        statusBadge: "Configured",
      },
      {
        id: "pay-runs",
        title: "Pay Runs",
        description: "Monthly payroll processing, direct deposit execution, and bank transfers",
        href: "/dashboard/payroll/pay-runs",
        icon: Receipt,
        stats: "August Pay Run Ready",
        statusBadge: "Next: Aug 30",
      },
      {
        id: "tax",
        title: "Tax & Compliance",
        description: "TDS, PF, ESI, Professional Tax, and statutory government filings",
        href: "/dashboard/payroll/tax",
        icon: FileText,
        stats: "100% Tax Compliant",
        statusBadge: "Verified",
      },
      {
        id: "payslips",
        title: "Payslips",
        description: "Digital payslip distribution, tax computation sheets, and YTD summaries",
        href: "/dashboard/payroll/payslips",
        icon: FileCheck,
        stats: "Auto-Delivered",
        statusBadge: "Secured",
      },
    ],
  },
  {
    id: "performance",
    title: "Performance",
    href: "/dashboard/performance",
    icon: TrendingUp,
    description: "OKRs, continuous performance feedback, appraisal cycles & skill matrices",
    subModules: [
      {
        id: "goals",
        title: "Goal Tracking (OKRs)",
        description: "Company, department, and individual OKRs alignment and progress tracking",
        href: "/dashboard/performance/goals",
        icon: Target,
        stats: "84% Target Met",
        statusBadge: "Q3 Active",
      },
      {
        id: "reviews",
        title: "Review Cycles",
        description: "Annual appraisals, mid-year check-ins, and performance calibration",
        href: "/dashboard/performance/reviews",
        icon: Award,
        stats: "H2 Review Open",
        statusBadge: "Active Cycle",
      },
      {
        id: "feedback",
        title: "360 Feedback",
        description: "Peer reviews, upward feedback, continuous praise, and manager check-ins",
        href: "/dashboard/performance/feedback",
        icon: MessageSquare,
        stats: "340 Feedbacks",
        statusBadge: "Continuous",
      },
      {
        id: "skills",
        title: "Skill Matrix",
        description: "Competency frameworks, skill gaps analysis, and growth pathways",
        href: "/dashboard/performance/skills",
        icon: Medal,
        stats: "124 Competencies",
        statusBadge: "Mapped",
      },
    ],
  },
  {
    id: "documents",
    title: "Documents",
    href: "/dashboard/documents",
    icon: FileText,
    description: "Enterprise document management, offer letters, contracts, templates & digital signatures",
    subModules: [
      {
        id: "employees",
        title: "Employee Documents",
        description: "Personal IDs, educational degrees, passport copies, and tax certificates",
        href: "/dashboard/documents/employees",
        icon: Contact,
        stats: "3,840 Files",
        statusBadge: "Verified",
      },
      {
        id: "offer-letters",
        title: "Offer Letters",
        description: "Generated candidate offer letters, compensation attachments, and acceptance status",
        href: "/dashboard/documents/offer-letters",
        icon: FilePlus,
        stats: "124 Issued",
        statusBadge: "E-Signed",
      },
      {
        id: "contracts",
        title: "Employment Contracts",
        description: "Standard employment contracts, non-compete agreements, and NDAs",
        href: "/dashboard/documents/contracts",
        icon: FileLock,
        stats: "1,248 Contracts",
        statusBadge: "Legally Binding",
      },
      {
        id: "policies",
        title: "Company Policies",
        description: "Employee handbook, code of conduct, remote work, and POSH policy documents",
        href: "/dashboard/documents/policies",
        icon: ScrollText,
        stats: "18 Handbooks",
        statusBadge: "Published",
      },
      {
        id: "certificates",
        title: "Certificates & Badges",
        description: "Experience letters, relieving certificates, and training completion badges",
        href: "/dashboard/documents/certificates",
        icon: Award,
        stats: "480 Issued",
        statusBadge: "Automated",
      },
      {
        id: "templates",
        title: "Letter Templates",
        description: "Standardized document templates for HR verification letters and NOCs",
        href: "/dashboard/documents/templates",
        icon: FileCode,
        stats: "24 Templates",
        statusBadge: "Configured",
      },
      {
        id: "digital-signatures",
        title: "Digital Signatures",
        description: "Cryptographic e-signature tracking, pending signer status, and audit trail",
        href: "/dashboard/documents/digital-signatures",
        icon: BadgeCheck,
        stats: "99.2% Signed",
        statusBadge: "eSign Audit",
      },
    ],
  },

  {
    id: "ai-workforce",
    title: "AI Workforce",
    href: "/dashboard/ai-workforce",
    icon: Sparkles,
    description: "Autonomous HR AI agents, automated workflow orchestration & predictive analytics",
    subModules: [
      {
        id: "agents",
        title: "AI Agents",
        description: "Autonomous HR copilot, onboarding bot, policy assistant, and query resolver",
        href: "/dashboard/ai-workforce/agents",
        icon: Bot,
        stats: "4 Agents Live",
        statusBadge: "99.2% Accuracy",
      },
      {
        id: "workflows",
        title: "Automation Workflows",
        description: "No-code event triggers, cross-department automations, and instant alerts",
        href: "/dashboard/ai-workforce/workflows",
        icon: Zap,
        stats: "48 Workflows Active",
        statusBadge: "2.4k Ops/Day",
      },
      {
        id: "analytics",
        title: "People Analytics AI",
        description: "Attrition risk prediction, sentiment analysis, and talent forecasting",
        href: "/dashboard/ai-workforce/analytics",
        icon: Brain,
        stats: "Predictive Models",
        statusBadge: "AI Powered",
      },
      {
        id: "copilots",
        title: "Smart Co-Pilots",
        description: "Interactive AI co-pilots for managers, recruiters, and HR business partners",
        href: "/dashboard/ai-workforce/copilots",
        icon: Cpu,
        stats: "Available 24/7",
        statusBadge: "Active",
      },
    ],
  },
  {
    id: "communication",
    title: "Communication",
    href: "/dashboard/communication",
    icon: Megaphone,
    description: "Company announcements, broadcasts, employee surveys, polls & campaign history",
    subModules: [
      {
        id: "announcements",
        title: "Announcements",
        description: "Official company notices, policy updates, and executive broadcasts",
        href: "/dashboard/communication/announcements",
        icon: Megaphone,
        stats: "0 Active",
        statusBadge: "Company Wide",
      },
      {
        id: "news",
        title: "Company News",
        description: "Internal newsletter, department highlights, and CEO town hall notes",
        href: "/dashboard/communication/news",
        icon: Newspaper,
        stats: "Digest",
        statusBadge: "Published",
      },
      {
        id: "broadcast",
        title: "Broadcast Messages",
        description: "Multi-channel SMS, email, and instant push notification broadcasts",
        href: "/dashboard/communication/broadcast",
        icon: Radio,
        stats: "SMS & Email",
        statusBadge: "Multi-channel",
      },
      {
        id: "surveys",
        title: "Employee Surveys",
        description: "Workforce pulse surveys, engagement scores, and feedback collection",
        href: "/dashboard/communication/surveys",
        icon: MessageSquare,
        stats: "0% Response",
        statusBadge: "Active",
      },
      {
        id: "polls",
        title: "Employee Polls",
        description: "Quick 1-click workforce polls, voting results, and sentiment tracking",
        href: "/dashboard/communication/polls",
        icon: Target,
        stats: "0 Live Polls",
        statusBadge: "Voting Open",
      },
      {
        id: "templates",
        title: "Message Templates",
        description: "Pre-approved email, SMS, and broadcast layout templates",
        href: "/dashboard/communication/templates",
        icon: FileText,
        stats: "0 Templates",
        statusBadge: "Standardized",
      },
      {
        id: "history",
        title: "Delivery History",
        description: "Message dispatch logs, read receipts, and delivery success metrics",
        href: "/dashboard/communication/history",
        icon: History,
        stats: "0 Delivered",
        statusBadge: "Sent Logs",
      },
      {
        id: "helpdesk-hub",
        title: "Helpdesk",
        description: "Support tickets, IT requests, and issue tracking",
        href: "/dashboard/helpdesk",
        icon: Ticket,
        stats: "Ticket Queue",
        statusBadge: "Linked",
      },
    ],
  },
  {
    id: "compliance",
    title: "Compliance",
    href: "/dashboard/compliance",
    icon: ShieldCheck,
    description: "Labor laws, regulatory mandates, audit trail logs & secure document vault",
    subModules: [
      {
        id: "laws",
        title: "Labor Laws & Policies",
        description: "Regional employment standards, statutory guidelines, and policy handbook",
        href: "/dashboard/compliance/laws",
        icon: FileLock,
        stats: "Global Standards",
        statusBadge: "Up to Date",
      },
      {
        id: "audit-logs",
        title: "Audit Trail",
        description: "Immutable system activity logs, access logs, and data modification history",
        href: "/dashboard/compliance/audit-logs",
        icon: History,
        stats: "SOC 2 Type II",
        statusBadge: "Logging Active",
      },
      {
        id: "documents",
        title: "Document Vault",
        description: "Encrypted repository for NDAs, agreements, certificates, and contracts",
        href: "/dashboard/compliance/documents",
        icon: FolderLock,
        stats: "256-bit AES",
        statusBadge: "Encrypted",
      },
      {
        id: "risks",
        title: "Risk Management",
        description: "Policy breach monitoring, data leak protection, and compliance alerts",
        href: "/dashboard/compliance/risks",
        icon: AlertTriangle,
        stats: "0 Critical Risks",
        statusBadge: "Protected",
      },
    ],
  },
  {
    id: "policies",
    title: "Policy Center",
    href: "/dashboard/policies",
    icon: ScrollText,
    description: "Central repository for corporate HR, payroll, attendance, leave & IT security policies",
    subModules: [
      {
        id: "hr",
        title: "HR Policies",
        description: "Employee handbook, code of conduct, remote work, and anti-harassment guidelines",
        href: "/dashboard/policies/hr",
        icon: ScrollText,
        stats: "12 Policies",
        statusBadge: "Published",
      },
      {
        id: "payroll",
        title: "Payroll Policies",
        description: "Salary disbursement timelines, statutory tax deductions, and expense guidelines",
        href: "/dashboard/policies/payroll",
        icon: DollarSign,
        stats: "6 Policies",
        statusBadge: "Audited",
      },
      {
        id: "attendance",
        title: "Attendance Policies",
        description: "Standard shift timings, late mark thresholds, and remote check-in rules",
        href: "/dashboard/policies/attendance",
        icon: Clock,
        stats: "4 Policies",
        statusBadge: "Active",
      },
      {
        id: "leave",
        title: "Leave Policies",
        description: "Paid leave accruals, casual leave carryover rules, and parental leave benefits",
        href: "/dashboard/policies/leave",
        icon: CalendarCheck,
        stats: "8 Policies",
        statusBadge: "Configured",
      },
      {
        id: "security",
        title: "Security Policies",
        description: "SOC2 compliance requirements, password rotation, and data protection rules",
        href: "/dashboard/policies/security",
        icon: ShieldCheck,
        stats: "5 Policies",
        statusBadge: "Enforced",
      },
    ],
  },

  {
    id: "engagement",
    title: "Employee Engagement",
    href: "/dashboard/engagement",
    icon: HeartHandshake,
    description: "Recognition wall, peer rewards, achievement badges, pulse surveys & milestones",
    subModules: [
      {
        id: "recognition",
        title: "Recognition Wall",
        description: "Public peer shoutouts, kudos feed, and executive appreciation notes",
        href: "/dashboard/engagement/recognition",
        icon: HeartHandshake,
        stats: "180 Shoutouts",
        statusBadge: "Active Feed",
      },
      {
        id: "rewards",
        title: "Peer Rewards",
        description: "Redeemable reward points, gift vouchers, and performance bonuses",
        href: "/dashboard/engagement/rewards",
        icon: Gift,
        stats: "4,200 Pts Given",
        statusBadge: "Redeemable",
      },
      {
        id: "badges",
        title: "Achievement Badges",
        description: "Gamified badges for innovation, leadership, teamwork, and years of service",
        href: "/dashboard/engagement/badges",
        icon: Award,
        stats: "48 Badges",
        statusBadge: "Gamified",
      },
      {
        id: "surveys",
        title: "Pulse Surveys",
        description: "Continuous employee sentiment pulse surveys and eNPS tracking",
        href: "/dashboard/engagement/surveys",
        icon: MessageSquare,
        stats: "86% eNPS",
        statusBadge: "High Pulse",
      },
      {
        id: "events",
        title: "Engagement Events",
        description: "Team offsites, birthday celebrations, and work anniversary honors",
        href: "/dashboard/engagement/events",
        icon: PartyPopper,
        stats: "12 Events",
        statusBadge: "Scheduled",
      },
    ],
  },
  {
    id: "reports",
    title: "Reports",
    href: "/dashboard/reports",
    icon: BarChart3,
    description: "Comprehensive reporting suite, headcount metrics, financial analytics & exports",
    subModules: [
      {
        id: "executive",
        title: "Executive Summary",
        description: "C-suite strategic overview of headcount, attrition, payroll spend & AI impact",
        href: "/dashboard/reports/executive",
        icon: Briefcase,
        stats: "C-Suite",
        statusBadge: "Live",
      },
      {
        id: "headcount",
        title: "Headcount Analytics",
        description: "Growth trends, department distribution, turnover rate & gender diversity",
        href: "/dashboard/reports/headcount",
        icon: Users2,
        stats: "1,248 Staff",
        statusBadge: "Real-time",
      },
      {
        id: "employees",
        title: "Employee Roster",
        description: "Granular employee directory, joining dates & employment status",
        href: "/dashboard/reports/employees",
        icon: Contact,
        stats: "Full Directory",
        statusBadge: "Active",
      },
      {
        id: "attendance",
        title: "Attendance Audit",
        description: "Absenteeism trends, late arrival metrics & biometric punch logs",
        href: "/dashboard/reports/attendance",
        icon: Calendar,
        stats: "96.4% Present",
        statusBadge: "Automated",
      },
      {
        id: "leave",
        title: "Leave Utilization",
        description: "Paid time off, accrual balances, approval velocity & holiday calendar",
        href: "/dashboard/reports/leave",
        icon: CalendarDays,
        stats: "420 Days Used",
        statusBadge: "Tracked",
      },
      {
        id: "payroll",
        title: "Payroll & Taxes",
        description: "Monthly payout reports, TDS tax breakdown & PF/ESI statutory contributions",
        href: "/dashboard/reports/payroll",
        icon: DollarSign,
        stats: "$482.5k Run",
        statusBadge: "Audited",
      },
      {
        id: "recruitment",
        title: "Recruitment Pipeline",
        description: "Open requisitions, candidate conversion funnel & time-to-hire",
        href: "/dashboard/reports/recruitment",
        icon: UserPlus,
        stats: "24 Open Roles",
        statusBadge: "Hiring",
      },
      {
        id: "onboarding",
        title: "New Hire Onboarding",
        description: "Orientation progress, verification docs & hardware dispatch",
        href: "/dashboard/reports/onboarding",
        icon: UserCheck,
        stats: "12 Joining",
        statusBadge: "98% Verified",
      },
      {
        id: "performance",
        title: "Performance & OKRs",
        description: "Goal completion rates, 360 review ratings & skill matrices",
        href: "/dashboard/reports/performance",
        icon: Award,
        stats: "84.2% Goals",
        statusBadge: "H2 Cycle",
      },
      {
        id: "learning",
        title: "Learning & Upskilling",
        description: "Course completions, compliance certificates & learning hours",
        href: "/dashboard/reports/learning",
        icon: GraduationCap,
        stats: "3.4k Hours",
        statusBadge: "Active",
      },
      {
        id: "assets",
        title: "Asset Allocation",
        description: "Hardware inventory, depreciation schedules & lost asset audits",
        href: "/dashboard/reports/assets",
        icon: Package,
        stats: "1.4k Assets",
        statusBadge: "$1.4M Value",
      },
      {
        id: "compliance",
        title: "Compliance Audit",
        description: "Labor law adherence, statutory tax filing logs & SOC2 audit scores",
        href: "/dashboard/reports/compliance",
        icon: ShieldCheck,
        stats: "99.8% Index",
        statusBadge: "SOC2 Type II",
      },
      {
        id: "ai-workforce",
        title: "AI Workforce Impact",
        description: "Autonomous bot executions, workflow automation hours & response speed",
        href: "/dashboard/reports/ai-workforce",
        icon: Bot,
        stats: "2.4k Ops/Day",
        statusBadge: "AI Powered",
      },
      {
        id: "attrition",
        title: "Attrition & Exit Risk",
        description: "Turnover rates by department, exit reasons & predictive flight risk",
        href: "/dashboard/reports/attrition",
        icon: TrendingDown,
        stats: "4.2% Rate",
        statusBadge: "Low Risk",
      },
      {
        id: "departments",
        title: "Department Summary",
        description: "Business units, cost centers & departmental leadership metrics",
        href: "/dashboard/reports/departments",
        icon: Building2,
        stats: "18 Units",
        statusBadge: "Active",
      },
      {
        id: "branches",
        title: "Branch & Campus Site",
        description: "Global site counts, office occupancy rates & regional distribution",
        href: "/dashboard/reports/branches",
        icon: Building,
        stats: "8 Campuses",
        statusBadge: "82% Occupancy",
      },
      {
        id: "organization",
        title: "Organization Hierarchy",
        description: "Span of control metrics, management levels & reporting lines",
        href: "/dashboard/reports/organization",
        icon: FolderTree,
        stats: "6 Levels",
        statusBadge: "Structured",
      },
      {
        id: "overtime",
        title: "Overtime Payouts",
        description: "Extra hours logged, manager approvals & hourly workload metrics",
        href: "/dashboard/reports/overtime",
        icon: Clock4,
        stats: "1.2k OT Hrs",
        statusBadge: "$34.8k Payout",
      },
      {
        id: "audit",
        title: "System Audit Trail",
        description: "Immutable admin action history, data changes & security policy logs",
        href: "/dashboard/reports/audit",
        icon: History,
        stats: "142k Logs",
        statusBadge: "Immutable",
      },
      {
        id: "activity",
        title: "User Activity Logs",
        description: "Active session logs, platform feature usage & login geographic breakdown",
        href: "/dashboard/reports/activity",
        icon: Activity,
        stats: "1.1k DAU",
        statusBadge: "Active",
      },
      {
        id: "builder",
        title: "Custom Report Builder",
        description: "Power BI style drag-and-drop query builder with custom filters",
        href: "/dashboard/reports/builder",
        icon: SlidersHorizontal,
        stats: "Query Engine",
        statusBadge: "Interactive",
      },
      {
        id: "scheduled",
        title: "Scheduled Auto-Reports",
        description: "Automated recurring email deliveries (Daily, Weekly, Monthly)",
        href: "/dashboard/reports/scheduled",
        icon: Calendar,
        stats: "14 Jobs",
        statusBadge: "Automated",
      },
      {
        id: "export",
        title: "Central Export Center",
        description: "Bulk data download hub for PDF, Excel, and CSV archive exports",
        href: "/dashboard/reports/export",
        icon: Download,
        stats: "420 Exports",
        statusBadge: "Multi-Format",
      },
    ],
  },
  {
    id: "integrations",
    title: "Integrations",
    href: "/dashboard/integrations",
    icon: Layers,
    description: "Connect identity providers, ERP accounting systems, Slack, Microsoft Teams & APIs",
    subModules: [
      {
        id: "sso",
        title: "Identity & SSO",
        description: "Okta, Microsoft Entra ID, Google Workspace, and SAML 2.0 / OIDC integrations",
        href: "/dashboard/integrations/sso",
        icon: Key,
        stats: "Okta / Entra Connected",
        statusBadge: "Active SSO",
      },
      {
        id: "accounting",
        title: "Accounting & ERP",
        description: "QuickBooks, SAP, NetSuite, and Xero automated payroll ledger sync",
        href: "/dashboard/integrations/accounting",
        icon: Database,
        stats: "NetSuite Synced",
        statusBadge: "Auto Sync",
      },
      {
        id: "communication",
        title: "Communication & Slack",
        description: "Slack bot notifications, Microsoft Teams apps, and email notification gateways",
        href: "/dashboard/integrations/communication",
        icon: MessageCircle,
        stats: "Slack & Teams Live",
        statusBadge: "Connected",
      },
      {
        id: "api",
        title: "Webhooks & API",
        description: "RESTful API keys, webhook endpoints, rate limits, and developer documentation",
        href: "/dashboard/integrations/api",
        icon: Code2,
        stats: "v2 API Live",
        statusBadge: "Developer",
      },
    ],
  },
  {
    id: "settings",
    title: "Settings",
    href: "/dashboard/settings",
    icon: Settings,
    description: "Configure tenant workspace, roles & permissions, security policies & billing",
    subModules: [
      {
        id: "organization",
        title: "Organization Profile",
        description: "Company details, legal name, tax IDs, brand themes, and domain configuration",
        href: "/dashboard/settings/organization",
        icon: Building,
        stats: "Verified",
        statusBadge: "Verified",
      },
      {
        id: "roles",
        title: "Roles & Permissions",
        description: "Granular RBAC matrix, custom admin roles, and permission assignments",
        href: "/dashboard/settings/roles",
        icon: Shield,
        stats: "5 Roles",
        statusBadge: "RBAC Enforced",
      },
      {
        id: "security",
        title: "Security & MFA",
        description: "Enforce multi-factor authentication, IP whitelisting, and password policies",
        href: "/dashboard/settings/security",
        icon: Lock,
        stats: "MFA Active",
        statusBadge: "Secure",
      },
      {
        id: "billing",
        title: "Billing & Subscriptions",
        description: "Enterprise tier plan, active seat usage, invoice history, and payment methods",
        href: "/dashboard/settings/billing",
        icon: BillingIcon,
        stats: "Enterprise Tier",
        statusBadge: "Active Sub",
      },
    ],
  },
];

export function getNavItemByHref(href: string): SidebarNavItem | undefined {
  return SIDEBAR_NAV_ITEMS.find(
    (item) => item.href === href || (item.href !== "/dashboard" && href.startsWith(item.href)),
  );
}

export function getSubModuleByHref(href: string): SubModuleItem | undefined {
  for (const navItem of SIDEBAR_NAV_ITEMS) {
    const sub = navItem.subModules.find((s) => s.href === href);
    if (sub) return sub;
  }
  return undefined;
}
