export interface ReportMeta {
  id: string;
  title: string;
  category: "Executive" | "Workforce" | "Operations" | "Financial" | "AI & Audit";
  description: string;
  href: string;
  iconName: string;
  isPinned?: boolean;
  isFavorite?: boolean;
  lastGenerated: string;
  exportFormat: "PDF" | "Excel" | "CSV";
  downloadsCount: number;
}

export const REPORTS_CATALOGUE: ReportMeta[] = [
  {
    id: "exec",
    title: "Executive Summary Report",
    category: "Executive",
    description: "C-suite strategic overview of headcount, attrition, payroll spend, hiring cost & AI impact",
    href: "/dashboard/reports/executive",
    iconName: "Briefcase",
    isPinned: true,
    isFavorite: true,
    lastGenerated: "Today at 09:30 AM",
    exportFormat: "PDF",
    downloadsCount: 142,
  },
  {
    id: "headcount",
    title: "Headcount & Growth Analytics",
    category: "Workforce",
    description: "Employee headcount expansion trends, department ratios & diversity telemetry",
    href: "/dashboard/reports/headcount",
    iconName: "Users2",
    isPinned: true,
    isFavorite: true,
    lastGenerated: "Today at 08:45 AM",
    exportFormat: "Excel",
    downloadsCount: 98,
  },
  {
    id: "employees",
    title: "Employee Roster & Demographics",
    category: "Workforce",
    description: "Granular employee directory, joining dates, employment status & gender ratio",
    href: "/dashboard/reports/employees",
    iconName: "Contact",
    isPinned: false,
    isFavorite: true,
    lastGenerated: "Yesterday at 05:20 PM",
    exportFormat: "CSV",
    downloadsCount: 76,
  },
  {
    id: "attendance",
    title: "Attendance & Shift Audit",
    category: "Operations",
    description: "Daily check-in logs, biometric sync rate, late arrivals & missing punch alerts",
    href: "/dashboard/reports/attendance",
    iconName: "Clock",
    isPinned: true,
    isFavorite: false,
    lastGenerated: "Today at 10:15 AM",
    exportFormat: "Excel",
    downloadsCount: 120,
  },
  {
    id: "leave",
    title: "Leave Utilization & Balances",
    category: "Operations",
    description: "Paid leave consumption, accrual balances, approval velocity & holiday calendar",
    href: "/dashboard/reports/leave",
    iconName: "CalendarDays",
    isPinned: false,
    isFavorite: false,
    lastGenerated: "Aug 01, 2026",
    exportFormat: "PDF",
    downloadsCount: 54,
  },
  {
    id: "payroll",
    title: "Payroll & Compensation Audit",
    category: "Financial",
    description: "Salary disbursement breakdown, taxes, PF/ESI statutory contributions & bonuses",
    href: "/dashboard/reports/payroll",
    iconName: "DollarSign",
    isPinned: true,
    isFavorite: true,
    lastGenerated: "Today at 07:00 AM",
    exportFormat: "Excel",
    downloadsCount: 210,
  },
  {
    id: "recruitment",
    title: "Recruitment Pipeline & Cost",
    category: "Workforce",
    description: "Open requisitions, candidate conversion funnel, offer acceptance & time-to-hire",
    href: "/dashboard/reports/recruitment",
    iconName: "UserPlus",
    isPinned: false,
    isFavorite: true,
    lastGenerated: "Jul 31, 2026",
    exportFormat: "PDF",
    downloadsCount: 65,
  },
  {
    id: "onboarding",
    title: "New Hire Onboarding Tracker",
    category: "Workforce",
    description: "Orientation progress, verification document completion & hardware dispatch",
    href: "/dashboard/reports/onboarding",
    iconName: "UserCheck",
    isPinned: false,
    isFavorite: false,
    lastGenerated: "Aug 01, 2026",
    exportFormat: "CSV",
    downloadsCount: 42,
  },
  {
    id: "performance",
    title: "Performance & Review Ratings",
    category: "Workforce",
    description: "OKR goal completion rates, 360 review score distributions & skill matrices",
    href: "/dashboard/reports/performance",
    iconName: "Award",
    isPinned: false,
    isFavorite: false,
    lastGenerated: "Jul 29, 2026",
    exportFormat: "PDF",
    downloadsCount: 88,
  },
  {
    id: "learning",
    title: "Learning & Upskilling Metrics",
    category: "Workforce",
    description: "Course enrollment velocity, compliance training completions & learning hours",
    href: "/dashboard/reports/learning",
    iconName: "GraduationCap",
    isPinned: false,
    isFavorite: false,
    lastGenerated: "Jul 28, 2026",
    exportFormat: "Excel",
    downloadsCount: 38,
  },
  {
    id: "assets",
    title: "Asset Allocation & Valuation",
    category: "Operations",
    description: "Hardware inventory distribution, depreciation schedules & lost asset logs",
    href: "/dashboard/reports/assets",
    iconName: "Package",
    isPinned: false,
    isFavorite: true,
    lastGenerated: "Today at 09:00 AM",
    exportFormat: "Excel",
    downloadsCount: 94,
  },
  {
    id: "compliance",
    title: "Labor Law & Audit Compliance",
    category: "AI & Audit",
    description: "Statutory filing compliance scores, policy violations & SOC2 security audit trail",
    href: "/dashboard/reports/compliance",
    iconName: "ShieldCheck",
    isPinned: true,
    isFavorite: false,
    lastGenerated: "Today at 06:30 AM",
    exportFormat: "PDF",
    downloadsCount: 115,
  },
  {
    id: "ai-workforce",
    title: "AI Agent Utilization & Impact",
    category: "AI & Audit",
    description: "Autonomous HR bot task executions, workflow automation hours & response time",
    href: "/dashboard/reports/ai-workforce",
    iconName: "Bot",
    isPinned: true,
    isFavorite: true,
    lastGenerated: "Today at 10:30 AM",
    exportFormat: "PDF",
    downloadsCount: 180,
  },
  {
    id: "attrition",
    title: "Attrition Risk & Exit Analysis",
    category: "Workforce",
    description: "Turnover rates by department, exit interview reasons & predictive attrition",
    href: "/dashboard/reports/attrition",
    iconName: "TrendingDown",
    isPinned: false,
    isFavorite: false,
    lastGenerated: "Jul 30, 2026",
    exportFormat: "Excel",
    downloadsCount: 72,
  },
  {
    id: "departments",
    title: "Department Breakdown",
    category: "Workforce",
    description: "Departmental headcount, budget allocations & leadership metrics",
    href: "/dashboard/reports/departments",
    iconName: "Building2",
    isPinned: false,
    isFavorite: false,
    lastGenerated: "Aug 01, 2026",
    exportFormat: "CSV",
    downloadsCount: 30,
  },
  {
    id: "branches",
    title: "Branch & Campus Distribution",
    category: "Operations",
    description: "Global site counts, office occupancy rates & regional headcount comparison",
    href: "/dashboard/reports/branches",
    iconName: "Building",
    isPinned: false,
    isFavorite: false,
    lastGenerated: "Jul 27, 2026",
    exportFormat: "PDF",
    downloadsCount: 28,
  },
  {
    id: "organization",
    title: "Organization Structure Summary",
    category: "Workforce",
    description: "Span of control metrics, management levels & hierarchy distribution",
    href: "/dashboard/reports/organization",
    iconName: "FolderTree",
    isPinned: false,
    isFavorite: false,
    lastGenerated: "Jul 25, 2026",
    exportFormat: "PDF",
    downloadsCount: 22,
  },
  {
    id: "overtime",
    title: "Overtime & Extra Hours",
    category: "Financial",
    description: "Overtime payouts, manager approvals & hourly workload metrics",
    href: "/dashboard/reports/overtime",
    iconName: "Clock4",
    isPinned: false,
    isFavorite: false,
    lastGenerated: "Aug 01, 2026",
    exportFormat: "Excel",
    downloadsCount: 48,
  },
  {
    id: "audit",
    title: "System Security Audit Log",
    category: "AI & Audit",
    description: "Immutable admin action history, data access events & security policy logs",
    href: "/dashboard/reports/audit",
    iconName: "History",
    isPinned: false,
    isFavorite: false,
    lastGenerated: "Today at 10:00 AM",
    exportFormat: "CSV",
    downloadsCount: 60,
  },
  {
    id: "activity",
    title: "User Activity Telemetry",
    category: "AI & Audit",
    description: "Active session logs, platform feature usage & login geographic breakdown",
    href: "/dashboard/reports/activity",
    iconName: "Activity",
    isPinned: false,
    isFavorite: false,
    lastGenerated: "Today at 09:45 AM",
    exportFormat: "CSV",
    downloadsCount: 40,
  },
  {
    id: "builder",
    title: "Custom Report Builder",
    category: "Executive",
    description: "Power BI style drag-and-drop report builder with custom query filters",
    href: "/dashboard/reports/builder",
    iconName: "SlidersHorizontal",
    isPinned: true,
    isFavorite: true,
    lastGenerated: "Interactive Tool",
    exportFormat: "PDF",
    downloadsCount: 310,
  },
  {
    id: "scheduled",
    title: "Scheduled Auto-Reports",
    category: "Operations",
    description: "Manage automated recurring email deliveries (Daily, Weekly, Monthly)",
    href: "/dashboard/reports/scheduled",
    iconName: "Calendar",
    isPinned: true,
    isFavorite: false,
    lastGenerated: "Auto Engine Live",
    exportFormat: "PDF",
    downloadsCount: 155,
  },
  {
    id: "export",
    title: "Central Export Center",
    category: "Operations",
    description: "Bulk data download hub for PDF, Excel, and CSV archive exports",
    href: "/dashboard/reports/export",
    iconName: "Download",
    isPinned: false,
    isFavorite: false,
    lastGenerated: "Central Archive",
    exportFormat: "Excel",
    downloadsCount: 420,
  },
];

// Reusable mock data streams for charts
export const MONTHLY_HEADCOUNT_TREND = [
  { month: "Jan", headcount: 1100, hires: 45, exits: 12, payrollCost: 420000 },
  { month: "Feb", headcount: 1125, hires: 38, exits: 13, payrollCost: 435000 },
  { month: "Mar", headcount: 1150, hires: 42, exits: 17, payrollCost: 442000 },
  { month: "Apr", headcount: 1180, hires: 48, exits: 18, payrollCost: 456000 },
  { month: "May", headcount: 1205, hires: 35, exits: 10, payrollCost: 468000 },
  { month: "Jun", headcount: 1225, hires: 32, exits: 12, payrollCost: 475000 },
  { month: "Jul", headcount: 1248, hires: 30, exits: 7, payrollCost: 482500 },
];

export const DEPARTMENT_DISTRIBUTION = [
  { name: "Product Engineering", count: 640, budget: 280000, color: "#6366f1" },
  { name: "Information Technology", count: 210, budget: 95000, color: "#3b82f6" },
  { name: "Human Resources", count: 95, budget: 42000, color: "#ec4899" },
  { name: "Finance Operations", count: 140, budget: 68000, color: "#10b981" },
  { name: "Executive Office", count: 45, budget: 55000, color: "#8b5cf6" },
  { name: "Marketing & Growth", count: 118, budget: 52000, color: "#f59e0b" },
];

export const ATTENDANCE_WEEKLY_TREND = [
  { day: "Mon", present: 96.8, late: 2.1, absent: 1.1 },
  { day: "Tue", present: 97.4, late: 1.8, absent: 0.8 },
  { day: "Wed", present: 98.1, late: 1.2, absent: 0.7 },
  { day: "Thu", present: 96.2, late: 2.5, absent: 1.3 },
  { day: "Fri", present: 94.5, late: 3.8, absent: 1.7 },
];

export const AI_IMPACT_METRICS = [
  { month: "Mar", tasksAutomated: 1200, hoursSaved: 380, resolutionRate: 94.2 },
  { month: "Apr", tasksAutomated: 1650, hoursSaved: 510, resolutionRate: 96.5 },
  { month: "May", tasksAutomated: 1980, hoursSaved: 640, resolutionRate: 97.8 },
  { month: "Jun", tasksAutomated: 2200, hoursSaved: 710, resolutionRate: 98.6 },
  { month: "Jul", tasksAutomated: 2450, hoursSaved: 820, resolutionRate: 99.2 },
];
